# Criação de pipeline baseando-se no kubernetes

stages:
  - build
  - deploy

variables:
  VERSION: "1.0"

criar_imagens:
  stage: build
  tags:
    - gcp
  script:
  - docker build -t denilsonbonatti/bootcamp-micro1:$VERSION app
  - docker push denilsonbonatti/bootcamp-micro1:$VERSION
  - docker build -t denilsonbonatti/bootcamp-micro2:$VERSION app
  - docker push denilsonbonatti/bootcamp-micro2:$VERSION

 kunernetes:
  stage: deploy
  needs:
    - criar_imagens
  tags:
    - gcp
  script:
    - kubectl apply -f ./deploy-micro1.yml
    - kubectl apply -f ./deploy-micro2.yml
    - kubectl apply -f ./mysql.yml
    - kubectl apply -f ./lb_yml
  